# Generated by Django 5.0.6 on 2024-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="policy1",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="policy2",
        ),
        migrations.AddField(
            model_name="hospital",
            name="auto_collection_device",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="consent_and_legal_basis",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="consignment",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="destruction_procedure",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="has_homepage",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="has_policy",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="homepage_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="policy_changes",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="policy_name_use",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="processed_items",
            field=models.CharField(
                choices=[("O", "Yes"), ("F", "Partially"), ("X", "No")],
                default="X",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="processing_purpose",
            field=models.CharField(
                choices=[("O", "Yes"), ("F", "Partially"), ("X", "No")],
                default="X",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="relief_methods",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="responsible_person",
            field=models.CharField(
                choices=[("O", "Yes"), ("F", "Partially"), ("X", "No")],
                default="X",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="retention_period",
            field=models.CharField(
                choices=[("O", "Yes"), ("F", "Partially"), ("X", "No")],
                default="X",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="safety_measures",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="subject_rights",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="third_party_provision",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="video_processing",
            field=models.CharField(
                choices=[("O", "Yes"), ("X", "No")], default="X", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
